services:
  - type: web
    name: agentenotiongpt
    runtime: python3.11
    skipPoetryInstall: true
    buildCommand: |
      echo "🔧 Python version:"
      python3 --version
      echo "🔧 Pip version:"
      python3 -m pip --version
      echo "📦 Instalando dependências..."
      python3 -m pip install --upgrade pip
      python3 -m pip install -r requirements.txt
    startCommand: python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT
