services:
  - type: web
    name: agentenotiongpt
    runtime: python3.11
    env: python
    buildCommand: |
      python3 -m venv /opt/render/project/venv
      . /opt/render/project/venv/bin/activate
      pip install -r requirements.txt
    startCommand: |
      . /opt/render/project/venv/bin/activate
      python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    preDeployCommand: chmod +x predeploy.sh && ./predeploy.sh
    envVars:
      - key: PORT
        value: 10000
      - key: DISABLE_POETRY_CREATE
        value: true

